import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const router = useRouter();

  const { status } = useSession();

  if (status === "authenticated") {
    router.replace("/dashboard");
  }

  return (
    <div className="md:container mx-auto h-screen">
      <Head>
        <title>Bitso Token Manager</title>
        <meta content="Generated by Khuddite" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="flex flex-col gap-8 items-center justify-center h-full">
        <Image
          className="self-center mb-4"
          src="/bitso.png"
          alt="Next.js logo"
          width={240}
          height={240}
          priority
        />
        <h1 className="text-3xl ext-center">Welcome to Bitso Token Manager!</h1>

        <p className="text-xl text-center">
          Get started by connecting your wallet
        </p>

        <ConnectButton />
      </main>
    </div>
  );
};

export default Home;
